### ISSUE TITLE
1.3 Meeting minutes

### ISSUE THREAD

**Issue by Kai-i-i-i** [KotoneZQ/INF2001_P7-6_Project#1]
1. Task title ID: #01
2. What is the task about

> To take down discussion notes that have been mentioned in the client meeting for documentation

3. What are the goals of the task?
> To document the notes and suggestions that have been mentioned by the client during the Q&A session
4. Success or completion criteria
> Able to document notes that is beneficial for our project and understanding of the requirement
5. Allocated time
> 5 days (2 client meeting)
6. Start date and end date of the issue/task)

> Meeting with client @ 11.00am - 11.15am, 6 Sep, Wed (Zoom)

> Meeting with client @ 3.00pm - 3.15pm, 11 Sep, Mon (Physical)

7. What is the priority of the task

> High priority

Issue/Task Comments Template
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by KotoneZQ** [comment]
_6 Sep 2023 (Thurs)_

**How should the workload information be displayed on the landing page?** 
At the moment, he is not looking at the UI, more keen on capturing the functionality of the application
Can do a concept sketch to show what we are trying to show

**Is there any specific metrics we need to show?**
He wants clarity, important information to be shown. E.g who is working today
oversight of staff availability, maybe a pie chart

**Should there be any restrictions or validations on job allocation, such as minimum or maximum number of jobs that can be allocated in a week?** 
Focus more on the number of hours instead of the number of jobs allocated

**What kind of relevant information can we get to make the job assignments better?**
I didnt catch this at all, He said that the information is mostly about workload

**This app for the manager side they are able to view the lowest workload employees and so on, how does the system calculate this workload and determine which employee has the lowest workload?**
By the number of hours.

**Are there any specific conditions for highlighting staff with over 40 hours of allocated jobs?**
Highlighted employees are highlighted to make sure that the manager can change the schedule and balance out the work hours throughout the employees, to make it more fair

**Comment by Kai-i-i-i** [comment]
attended zoom - 6/9

**Comment by Jr-Goh** [comment]
attended zoom client meeting - 6/9

**Comment by KotoneZQ** [comment]
_Meeting Minutes (11 Sep, Mon)_
1. No preferences, Think as Default
Unable to meet the submission--> Case-by-Case basis
Think of mechanism to do it (for swapping)
2. No requirement in the technology, is a platform-based technology. Not too focused on GUI design but more on the functionality of the system
3. Visualization includes no of hours for each employees, no. of shifts (weekday/weekends), allow amendment if unbalanced
4. Warning mechanism includes facilities planning/scheduling
Indication such as unavailable to work
Backend stuffs such as maintainence
5. Management main objective is to balance overall workload of employees. Priority is the need of employee
6. Planning include fair backup/standby shifts (components)
7. Capture stability
Focus on variable, more on underwork or overwork in the service
8. Workload System. Concurrently can be planned and changed by employees/manager. Fixed

**Comment by brandonbljl** [comment]
attended client meeting

**Comment by Jr-Goh** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
Closed as Completed (11/9).
